### ISSUE TITLE
amoCRM убрал endpoint для получения информации об аккаунте

### ISSUE THREAD

**Issue by aibolik** [Bolid1/npm-api-client-amocrm#4]
https://www.amocrm.ru/api/accounts/domains/ - этот endpoint теперь дает 403 forbidden. Из-за этого авторизация не проходит, так как оно зависит от ответа этого endpoint-а.

Как я понял, этот endpoint используется только для того, чтобы достать полный адрес аккаунта. Временное решение было возвращать `"https://" + subdomain + ".amocrm.ru"` вместо того, чтобы делать запрос на тот endpoint.

@Bolid1  можете дать права на contribution? Мои интеграции сильно зависят от этой либы, и я бы хотел исправить этот баг и поддерживать проект в дальнейшем.

Спасибо

**Comment by Bolid1** [comment]
В GitHub есть возможность отправить pull-request из форка :-)
И `amocrm.ru` не подходит, т.к. домен верхнего уровня может быть `.com`.
В данном случае следует параметризовать домен верхнего уровня

**Comment by aibolik** [comment]
@Bolid1 окей, я просто думал проект не поддерживается уже :) 

а если делать запрос на `.com`, то он не будет работать?

> В данном случае следует параметризовать домен верхнего уровня

Здесь вы имеете ввиду типа чтобы домен который передается в параметрах был полностью с доменом верхнего уровня? Например `primer.amocrm.ru` или `primer.amocrm.com`?

И ещё вопрос, откуда вы взяли endpoint https://www.amocrm.ru/api/accounts/domains/?

Не смог найти в документации. Вчера он не работал(403 - forbidden), и пришлось делать хотфикс для некоторых вещей. А сегодня этот домен работает. Можно ли быть уверенным что он всегда будет работать(или где уточнить)?

**Comment by Bolid1** [comment]
Проект мною не используется, потому и не поддерживается :-)

> а если делать запрос на .com, то он не будет работать?

Да, amoCRM так устроена, что при запросе информации из `ru` аккаунта через домен `com` будет возвращаться ошибка авторизации. По крайней мере так было на момент написания библиотеки, возможно с тех пор что-то изменилось.

> Здесь вы имеете ввиду типа чтобы домен который передается в параметрах был полностью с доменом верхнего уровня? Например primer.amocrm.ru или primer.amocrm.com?
Да

> И ещё вопрос, откуда вы взяли endpoint https://www.amocrm.ru/api/accounts/domains/?
Если в документации нет, то нельзя быть уверенным.

Сейчас уже не помню зачем он был создан.

**Comment by aibolik** [comment]
Принял, спасибо за ответы.
